version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    s3:
      accesskey: REDACTED
      secretkey: REDACTED
      bucket: REDACTED
      encrypt: false
      secure: false
      v4auth: false
      rootdirectory: /registry2
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
auth:
  htpasswd:
    realm: basic-realm
    path: /htpasswd

